apiVersion: batch/v1
kind: Job
metadata:
  name: ckecli-etcd-snapshot-list
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        job-name: ckecli-etcd-snapshot-list
    spec:
      containers:
        - command:
            - ls
            - /etcd-backup
          image: quay.io/cybozu/etcd:3.3.9-4
          imagePullPolicy: IfNotPresent
          name: ckecli-etcd-snapshot-list
          volumeMounts:
            - mountPath: /etcd-backup
              name: etcd-backup
      restartPolicy: Never
      volumes:
        - name: etcd-backup
          persistentVolumeClaim:
            claimName: {{ .PVCName }}
