version: '2'
services:
  cke:
    container_name: cke
    image: quay.io/cybozu/cke:0
    user: "${UID}:${GID}"
    volumes:
      - ./cke.config.yml:/etc/cke/config.yml
    depends_on:
      - setup
    restart: always
  setup:
    container_name: setup
    image: quay.io/cybozu/ubuntu-debug:18.04
    user: "${UID}:${GID}"
    volumes:
      - ./bin:/usr/local/bin
      - ./setup:/opt/setup
      - ./cke.config.yml:/etc/cke/config.yml
    depends_on:
      - vault
      - etcd
      - setup-cke-tools
      - setup-etcd-tools
      - setup-vault-tools
    command: /opt/setup/setup.sh
  vault:
    container_name: vault
    image: quay.io/cybozu/vault:0.11
    user: "${UID}:${GID}"
    cap_add:
      - IPC_LOCK
    depends_on:
      - etcd
    volumes:
      - ./vault.hcl:/etc/vault/config.hcl
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    command: server -config=/etc/vault/config.hcl
  etcd:
    container_name: etcd
    image: quay.io/cybozu/etcd:3.3
    user: "${UID}:${GID}"
    volumes:
      - ./etcd-data:/data/etcd
      - ./etcd.conf.yml:/etc/etcd/etcd.conf.yml
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
    command: --config-file=/etc/etcd/etcd.conf.yml
  setup-cke-tools:
    image: quay.io/cybozu/cke:0
    user: "${UID}:${GID}"
    volumes:
      - ./bin:/host
    entrypoint:
      - /usr/local/cke/install-tools
  setup-vault-tools:
    image: quay.io/cybozu/vault:0.11
    user: "${UID}:${GID}"
    volumes:
      - ./bin:/host
    entrypoint:
      - /usr/local/vault/install-tools
  setup-etcd-tools:
    image: quay.io/cybozu/etcd:3.3
    user: "${UID}:${GID}"
    volumes:
      - ./bin:/host
    entrypoint:
      - /usr/local/etcd/install-tools
